---
- name: Configure Fileserver
  hosts: fileserver
  become: true
  tasks:
    # Update system files
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true

  # Install NFS and quote Tools 
    - name: Install NFS server
      ansible.builtin.apt:
        name: nfs-kernel-server
        state: present

    - name: Install quota tools
      ansible.builtin.apt:
        name: quota
        state: present

    - name: Show done message
      ansible.builtin.debug:
        msg: "=== NFS and Quota tools installed on Fileserver! =="