- name: Configure shares on Fileserver
  hosts: fileserver
  become: true
  
  
  tasks:
  # Create share directories
    - name: Create /shares
      ansible.builtin.file:
        name: /shares
        state: directory
        owner: root
        group: root
        mode: '0755'

    
    - name: Create /shares/Common
      ansible.builtin.file:
        name: /shares/Common
        state: directory
        owner: root
        group: users
        mode: '0775'


    - name: Create /shares/Legal
      ansible.builtin.file:
        name: /shares/Legal
        state: directory
        owner: root
        group: group-Legal
        mode: '0770'


    - name: Create /shares/Sales
      ansible.builtin.file:
        name: /shares/Sales
        state: directory
        owner: root
        group: group-Sales
        mode: '0770'
      
  
  # 0775: owner+group can read/write, others can read, 
  # 0770: owner+group can read/write, others have NO access


    
    - name: Show done message
      ansible.builtin.debug:
        msg: "=== Shared directories created! =="

    