- name: Configure shares on Fileserver
  hosts: fileserver
  become: true
  
  
  tasks:
    - name: Create /shares/Common
      ansible.builtin.file:
        name: /shares/Common
        state: directory
        owner: root
        group: users
        mode: '0775'


    - name: Create /shares/Legal
      ansible.builtin.file:
        name: /shares/Legal
        state: directory
        owner: root
        group: group-Legal
        mode: '0770'


    - name: Create /shares/Sales
      ansible.builtin.file:
        name: /shares/Sales
        state: directory
        owner: root
        group: group-Sales
        mode: '0770'
        
 
    - name: Show done message
      ansible.builtin.debug:
        msg: "=== Shared directories created! =="

    