---
- name: Configure NFS exports on Fileserver
  hosts: fileserver
  become: true
  vars:
    client_network: "{{ ansible_default_ipv4.network}}/24"

  tasks:
    # Configures NFS exports, adds the path to the exports file
    # Defines which directories are shared on the network
    - name: Add /Common to NFS exports
      ansible.builtin.lineinfile:
        path: /etc/exports
        line: "/shares/Common {{ client_network}}(rw,sync,no_subtree_check)"
        state: present
        create: yes

    - name: Add /Legal to NFS exports
      ansible.builtin.lineinfile:
        path: /etc/exports
        line: "/shares/Legal {{ client_network}}(rw,sync,no_subtree_check)"
        state: present
        
    - name: Add /Sales to NFS exports
      ansible.builtin.lineinfile:
        path: /etc/exports
        line: "/shares/Sales {{ client_network}}(rw,sync,no_subtree_check)"
        state: present

    # Applying the exports
    - name: Apply NFS exports
      ansible.builtin.command: exportfs -ra 
      # Note: this will always be reported as "changed" by Ansible
      
    - name: Start and enable NFS
      ansible.builtin.service:
        name: nfs-kernel-server
        state: started
        enabled: yes

    - name: Debug msg done
      ansible.builtin.debug:
        msg: "==== Directories are exported and NFS service enabled! ===="