---
- name: Create mounts on clients
  hosts: clients
  become: true

  tasks:
    - name: Create mount point for /Common
      ansible.builtin.file:
        name: /mnt/Common
        state: directory
        mode: '0755'
  
    - name: Create mount point for /Legal
      ansible.builtin.file:
        name: /mnt/Legal
        state: directory
        mode: '0755'

    - name: Create mount point for /Sales
      ansible.builtin.file:
        name: /mnt/Sales
        state: directory
        mode: '0755'      

    - name: Show done message
      ansible.builtin.debug:
        msg: "=== clients have their mounts created =="

        # Kan vi skriva ut varje klients hostname här? Det hade varit snyggt!