---
- name: Create NFS shares on clients
  hosts: clients
  become: true

  # Mounts /Common, /Legal, /Sales on both clients.
  # Directs the mounted directories to the respective directory in the fileserver.
  tasks:
    - name: Mount Common shares
      ansible.builtin.mount:
        path: /mnt/Common
        src: "{{ groups['fileserver'][0] }}:/shares/Common"
        fstype: nfs
        opts: rw,sync,hard
        state: mounted
  # sync: wait until the file is saved before confirming
  # hard: never give up if server goes down

    - name: Mount Legal shares
      ansible.builtin.mount:
        path: /mnt/Legal
        src: "{{ groups['fileserver'][0] }}:/shares/Legal"
        fstype: nfs
        opts: rw,sync,hard
        state: mounted

    - name: Mount Sales shares
      ansible.builtin.mount:
        path: /mnt/Sales
        src: "{{ groups['fileserver'][0] }}:/shares/Sales"
        fstype: nfs
        opts: rw,sync,hard
        state: mounted

        
    - name: Show the control message
      ansible.builtin.debug:
        msg: "==NFS shares on clients are mounted =="