---
- import_playbook: 01_nfs_install.yml
- import_playbook: 02_nfs_users.yml
- import_playbook: 03_nfs_setup_disk.yml
- import_playbook: 04_nfs_shares.yml
- import_playbook: 05_nfs_exports.yml
- import_playbook: 06_nfs_ufw.yml
- import_playbook: 07_client_install.yml
- import_playbook: 08_client_mount.yml
- import_playbook: 09_client_shares.yml
- import_playbook: 10_nfs_quotas.yml

