---
- import_playbook: 01_nfs_install.yml
- import_playbook: 02_nfs_users.yml
- import_playbook: 03_nfs_shares.yml
- import_playbook: 04_nfs_exports.yml
- import_playbook: 05_client_install.yml
- import_playbook: 06_client_mount.yml
- import_playbook: 07_client_shares.yml
- import_playbook: 08_nfs_quotas.yml
