---
- import_playbook: 01_nfs_install.yml
- import_playbook: 02_nfs_users.yml
- import_playbook: 03_nfs_share.yml
- import_playbook: 04_nfs_exports.yml
- import_playbook: 05_client_legal.yml
- import_playbook: 06_client_legal.yml
